version: '3.3'

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web-network

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf 
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=SGT
      - MYSQL_USER=sgt_user_db
      - MYSQL_PASSWORD=53Rr1Nh@
      - MYSQL_ROOT_PASSWORD=M@r14Db!
    networks:
      - web-network

#Docker Networks
networks:
  web-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local