version: '3.3'

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=SGT
      - MYSQL_USER=sgt_user_db
      - MYSQL_PASSWORD=53Rr1Nh@
      - MYSQL_ROOT_PASSWORD=M@r14Db!
