# Generated by Django 3.0.7 on 2020-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividadecomplementar',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=200)),
                ('cargahoraria', models.IntegerField(db_column='CargaHoraria')),
            ],
            options={
                'db_table': 'AtividadeComplementar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atividadeextracurricular',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=200)),
                ('tipo', models.CharField(db_column='Tipo', max_length=10)),
                ('bolsista', models.IntegerField(db_column='Bolsista')),
            ],
            options={
                'db_table': 'AtividadeExtraCurricular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('turno', models.CharField(db_column='Turno', max_length=10)),
            ],
            options={
                'db_table': 'Curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('matricula', models.AutoField(db_column='Matricula', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=200)),
                ('nomesocial', models.CharField(blank=True, db_column='NomeSocial', max_length=200, null=True)),
                ('datanascimento', models.DateField(db_column='DataNascimento')),
                ('gênero', models.CharField(db_column='Gênero', max_length=1)),
                ('anoingresso', models.IntegerField(db_column='AnoIngresso')),
                ('turnotrabalho', models.CharField(blank=True, db_column='TurnoTrabalho', max_length=10, null=True)),
                ('cidadeorigem', models.CharField(db_column='CidadeOrigem', max_length=100)),
                ('moraemserrinha', models.IntegerField(db_column='MoraEmSerrinha')),
                ('rendafamiliar', models.CharField(db_column='RendaFamiliar', max_length=10)),
                ('temposemestudar', models.IntegerField(blank=True, db_column='TempoSemEstudar', null=True)),
                ('tipoescolaensmedio', models.CharField(db_column='TipoEscolaEnsMedio', max_length=20)),
                ('motivoescolhacurso', models.CharField(db_column='MotivoEscolhaCurso', max_length=200)),
                ('expectativascurso', models.TextField(db_column='ExpectativasCurso')),
                ('subareasinteresse', models.TextField(db_column='SubAreasInteresse')),
                ('planoegresso', models.TextField(db_column='PlanoEgresso')),
                ('nomecursotecnico', models.CharField(blank=True, db_column='NomeCursoTecnico', max_length=200, null=True)),
                ('localcursotecnico', models.CharField(blank=True, db_column='LocalCursoTecnico', max_length=200, null=True)),
                ('nomegraduacao', models.CharField(blank=True, db_column='NomeGraduacao', max_length=200, null=True)),
                ('localgraduacao', models.CharField(blank=True, db_column='LocalGraduacao', max_length=200, null=True)),
                ('projetoextensao', models.TextField(blank=True, db_column='ProjetoExtensao', null=True)),
                ('dificuldadesensmedio', models.TextField(blank=True, db_column='DificuldadesEnsMedio', null=True)),
                ('dificuldadescurso', models.TextField(blank=True, db_column='DificuldadesCurso', null=True)),
                ('coeficienterendimento', models.FloatField(db_column='CoeficienteRendimento')),
                ('semestreatual', models.IntegerField(db_column='SemestreAtual')),
            ],
            options={
                'db_table': 'Discente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('cargahoraria', models.IntegerField(db_column='CargaHoraria')),
                ('horariosemana', models.CharField(db_column='HorarioSemana', max_length=20)),
                ('status', models.CharField(db_column='Status', max_length=20)),
            ],
            options={
                'db_table': 'Disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('siape', models.AutoField(db_column='SIAPE', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('perfil', models.CharField(db_column='Perfil', max_length=1)),
            ],
            options={
                'db_table': 'Docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estagioextracurricular',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=100)),
                ('remuneracao', models.FloatField(db_column='Remuneracao')),
                ('cargahoraria', models.IntegerField(db_column='CargaHoraria')),
                ('datainicio', models.DateField(db_column='DataInicio')),
                ('datafim', models.DateField(blank=True, db_column='DataFim', null=True)),
            ],
            options={
                'db_table': 'EstagioExtraCurricular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orientacaomatricula',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OrientacaoMatricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrientacaomatriculaDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'OrientacaoMatricula_Disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('legislacoesifbaiano', models.TextField(db_column='LegislacoesIFBaiano')),
                ('dificuldadessemestreatual', models.TextField(db_column='DificuldadesSemestreAtual')),
                ('acoes', models.TextField(db_column='Acoes')),
                ('sugestoesdifsemestre', models.TextField(db_column='SugestoesDifSemestre')),
                ('dificuldadescurso', models.TextField(db_column='DificuldadesCurso')),
                ('sugestoesdifcurso', models.TextField(db_column='SugestoesDifCurso')),
                ('observacoes', models.TextField(db_column='Observacoes')),
            ],
            options={
                'db_table': 'Tutoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutoriaDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Tutoria_Disciplina',
                'managed': False,
            },
        ),
    ]
