# Generated by Django 3.2.4 on 2021-06-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrientacaomatriculaDisciplina',
        ),
    ]
